---
title: "Dashboard en R"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
---

```{r setup, include=FALSE }

library(tidyverse)      
library(gargle)         
#library(funModeling)    
library(kableExtra)
library(plotly)
library(patchwork)
library(RColorBrewer)
library(flexdashboard)
library(extrafont)
library(scales)
#library(funModeling)
library(ggalt)



azul <- "#344D7E"
verde <-  "#4A9FC7"
gris <- "#75838F"
rosa1 <- "#B95192"
rosa2 <- "#EE5777"
naranja <- "#FF764C"
amarillo <- "#FFA600"
gris <- "#75838F"
lila <- "#755395"


# Estilo limpio con líneas de referencia verticales en gris claro
estilov <- theme(panel.grid = element_blank(),
                 plot.background = element_rect(fill = "#FBFCFC"),
                 panel.background = element_blank(),
                 panel.grid.major.x = element_line(color = "#AEB6BF"),
                 text = element_text(family = "Roboto"))

# Estilo limpio con líneas de referencia horizontales en gris claro
estiloh <- theme(panel.grid = element_blank(),
                 plot.background = element_rect(fill = "#FBFCFC"),
                 panel.background = element_blank(),
                 panel.grid.major.y = element_line(color = "#AEB6BF"),
                 text = element_text(family = "Roboto"))


fuente <- "Fuente: Elaboración propia"

```


```{r  include=FALSE}
original <- read.csv("Data.csv", stringsAsFactors = TRUE)
d1<- original

limpios <- make.names(colnames(d1))
colnames(d1) <- limpios
d1 <- d1%>% 
  rename(
  edad=  "ï..Age",
  rotacion= "Attrition",
  viaje_negocio="BusinessTravel",
  tasa_diaria="DailyRate", 
  departamento=Department,
  distancia=DistanceFromHome,
  educacion=Education,
  especialidad=EducationField,
  cuenta_empleado=EmployeeCount,
  dotacion=EmployeeNumber,
  clima=EnvironmentSatisfaction,
  genero=Gender,
  tasa_horaria=HourlyRate, 
  participacion=JobInvolvement,
  jerarquia=JobLevel,
  puesto=JobRole,
  satisfaccion=JobSatisfaction,
  est_civil=MaritalStatus,
  sueldo=MonthlyIncome,
  tasa_sueldo=MonthlyRate,
  companias_trabajadas=NumCompaniesWorked,
  mayor_18=Over18,
  hs_extras=OverTime,
  aumento_porcentual= PercentSalaryHike,
  desempeno=PerformanceRating, # no uso la ñ
  vinculo=RelationshipSatisfaction,
  horas=StandardHours,
  ESO= StockOptionLevel, # (Employee Stock Option),
  anios_trabajados=TotalWorkingYears,
  entrenamientos_ly=TrainingTimesLastYear, 
  bce_vida_trabajo= WorkLifeBalance,
  antiguedad=YearsAtCompany,
  antiguedad_puesto=YearsInCurrentRole,
  antiguedad_ult_promocion= YearsSinceLastPromotion,
  antiguedad_gte= YearsWithCurrManager
  )

d1<- d1 %>% 
  select(everything(),-cuenta_empleado,-horas,)
```

```{r  include=FALSE}
#Limpieza de Variables: 

#1- V. Viaje
# armo una escala

#no - poco - frecuente

d1<- d1 %>% 
 mutate(viaje_negocio = fct_collapse(viaje_negocio,"Poco"= "Travel_Rarely",
                                                     "Frecuente"="Travel_Frequently" ,
                                                     "No"="Non-Travel"  ))

#2-V. Dpto 

d1<- d1 %>% 
 mutate(departamento = fct_collapse(departamento,  "I&D"="Research & Development" , 
                                                   "HR"="Human Resources",
                                                    "Ventas"= "Sales"))

#3- V. Genero

d1<- d1 %>% 
 mutate(genero = fct_collapse(genero,  "Femenino"="Female" , 
                                                   "Masculino"="Male",
                                                    ))

#5-V. Puesto

d1<- d1 %>% 
 mutate(puesto = fct_collapse(puesto,  "Vendedor"="Sales Executive" , 
                                        "Investigador"="Research Scientist",
                                        "Tec_laboratorio"="Laboratory Technician",
                                        "Dir_Operativo"="Manufacturing Director",
                                        "Atencion_cliente"="Healthcare Representative",
                                        "Gerente"="Manedadr",
                                        "Comercial"="Sales Representative",
                                        "Director"="Research Director",
                                        "HR"="Human Resources"))

#6- V. Esta Civil

d1<- d1 %>% 
 mutate(est_civil = fct_collapse(est_civil,  "Casadx"="Married" , 
                                                   "Solterx"="Single",
                                                    "Divorciadx"= "Divorced"))

#7- V. Edad

d1<-d1%>% 
         mutate(edad_cat = case_when(
                                edad > 17 & edad <= 25 ~ "18-25",
                                edad > 25 & edad <= 35 ~ "26-35",
                                edad > 35 & edad <= 46 ~ "36-45",
                                edad > 45 & edad <= 50 ~ "46-50",
                                edad > 50 & edad <= 64 ~ "51-64",        
                                edad > 64             ~ "> 64"
                                )) %>% 
         mutate(edad_cat = factor(edad_cat,
         level = c("18-25","26-35", "36-45","46-50","51-64","> 64")
    )) 


#8- Especialidad
d1<- d1 %>% 
 mutate(especialidad = fct_collapse(especialidad,  "Ciencias"="Life Sciences" , 
                                                   "Medicina"="Medical",                                                                                      "Mkt"="Marketing",                                                                                         "HR"="Human Resources",
                                                   "Otros"="Other"
                                                    ))

#9- Rotacion

d1<- d1 %>% 
 mutate(rotacion = fct_collapse(rotacion,"Si"= "Yes"))


```



Especialidad
======================================================================

Column {data-width=650} {.tabset .tabset-fade}
-----------------------------------------------------------------------

###  Rotación

```{r}
d1%>% 
  rename(
  Especialidad=  "especialidad")%>%
  plot_ly(x = ~Especialidad, color  =~rotacion, colors = "Accent" )%>%
  layout(yaxis = list(title = 'Cantidad'))




```


###  Género

```{r}

g1<-
  d1 %>% 
    select(rotacion,genero,especialidad) %>%
    rename("Género"=genero) %>% 
    filter (rotacion=="Si") %>%
    group_by(especialidad,Género) %>% 
    summarise(Cantidad=n()) 

gender <- c("#8624F5", "#1FC3AA")

ggplot(data=g1,aes(x=especialidad,y = Cantidad  ,fill=Género))+
    geom_bar(stat="identity", position=position_dodge())+
  scale_fill_manual(values = gender) +
    ggtitle("Especialidad & Género ")+
  labs(x = "", y = "")


```


Column {data-width=350}
-----------------------------------------------------------------------

### Rotación

```{r}

g7<-d1%>% 
  select(rotacion)%>%
  group_by(rotacion)%>%
  summarise(counts = n()) %>%
  mutate(prop = (counts / sum(counts)) * 100) %>%
  arrange(desc(prop)) %>% 
ggplot(aes("", counts)) +
  geom_col(
    position = "fill",
    color = "black",
    width = 1,
    aes(fill = factor(rotacion))
  ) +
  geom_text(
    aes(label = str_c(round(prop), "%"), group = factor(rotacion)),
    position = position_fill(vjust = 0.5),
    color = "white",
    size = 6,
    show.legend = FALSE,
    fontface = "bold"
  ) +
  coord_polar(theta = "y") +
  theme_void() +
  scale_fill_manual (values = c(azul,verde)) +
  theme_void() +
  labs(
    title = "Rotación ",
    subtitle = "",
    caption = "",
    fill = ""
  )

g7
```



### Rotación 2

```{r}
g8<-d1%>% 
  select(rotacion)%>%
  group_by(rotacion)%>%
  summarise(counts = n()) %>%
  mutate(prop = (counts / sum(counts)) * 100) %>%
  arrange(desc(prop))

g8<-ggplot(g8, aes(x="", y=prop, fill=rotacion)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  theme(legend.position="none") +
  geom_text(aes(label = rotacion), color = "white", size=6)+
  scale_fill_brewer(palette="Set2")

g8

```



Ingresos
======================================================================

Column {data-width=650} {.tabset .tabset-fade}
-----------------------------------------------------------------------


###  Género
```{r}

ggplot(d1, aes(x=rotacion, y=sueldo, color=genero, fill=genero)) +
    geom_boxplot()


```


Departamento
======================================================================

Column {data-width=650} {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Departamento & Bajas

```{r}

g2<-d1%>% 
  filter(rotacion=="Si")%>%
  plot_ly(x = ~departamento, color  =~genero, colors = "Accent" )%>%
  layout(yaxis = list(title = 'Cantidad'))

g2
```



### Departamento & Activos 

```{r}
g3<-d1%>% 
  filter(rotacion=="No")%>%
  plot_ly(x = ~departamento, color  =~genero, colors = "Accent" )%>%
  layout(yaxis = list(title = 'Cantidad'))

g3

```



Horas Extras
======================================================================

Column {data-width=650}
-----------------------------------------------------------------------


###  Sueldos
```{r}

g6<-ggplot(d1, aes(x=hs_extras, y=sueldo, color=genero, fill=genero)) +
    geom_boxplot()
g6


```



Column {data-width=350}
-----------------------------------------------------------------------

### Bajas 

```{r}

g4<-d1 %>% 
  select(hs_extras, sueldo, genero, rotacion) %>% 
  filter(rotacion=="Si") %>% 
  ggplot( aes(x=hs_extras, y=sueldo, color=genero, fill=genero)) +
    geom_boxplot()+
    labs(title='Bajas')

g4
```



### Activos

```{r}
g5<-d1 %>% 
  select(hs_extras, sueldo, genero, rotacion) %>% 
  filter(rotacion=="No") %>% 
  ggplot( aes(x=hs_extras, y=sueldo, color=genero, fill=genero)) +
    geom_boxplot()+
   labs(title='Activos')

g5

```

Gap Salarial {data-orientation=rows}
==========================================================

Rows
--------------------------------------------------------

### Sueldo Promedio Mujeres & Bajas

```{r}

brecha <- d1 %>% 
  select(sueldo, genero,rotacion) %>% 
  filter(rotacion=="Si") %>% 
  group_by(genero) %>% 
  summarise(media_salarial = mean(sueldo))

brecha_graf <- brecha %>% 
  pivot_wider(., names_from = genero, values_from = media_salarial) %>% 
  mutate(brecha = percent((Masculino-Femenino)/Masculino, 1),
         x = (Masculino + Femenino)/2,
         gap = Femenino/Masculino)

# Calcular el indicador de brecha salarial 
brecha_promedio <- round(mean(brecha_graf$gap*100))



```

```{r}
### Sueldo Promedio Mujeres

valueBox(round(mean(brecha_graf$Femenino)), icon = "fa-female", color = "#8624F5")

```


### Sueldo Promedio Hombres & Bajas

```{r}
### Sueldo Promedio Hombres
valueBox(round(mean(brecha_graf$Masculino)), icon = "fa-male", color = "#1FC3AA")
```


Column 
-----------------------------------------------

```{r}

d1%>% 
  filter(rotacion=="Si") %>% 
  rename( Género=  "genero")%>%
  plot_ly(x = ~Género, color  =~rotacion, colors = "Accent" )#%>%
 # layout(yaxis = list(title = ''))

```


